dependencies:
  - aopo
  - bao
  - bfo
  - bto
  - ccont
  - chebi
  - cheminf
  - chmo
  - cito
  - clo
  - efo
  - envo
  - fabio
  - go
  - iao
  - ncit
  - npo
  - oae
  - obcs
  - obi
  - pato
  - ro
  - sio
  - uberon
  - uo
api_key: xxxx 
classes:
 chemical substance:
  - CHEBI 
  - http://purl.obolibrary.org/obo/CHEBI_59999
 molecular entity:
  - CHEBI
  - http://purl.obolibrary.org/obo/CHEBI_23367
 material entity: 
  - BFO 
  - http://purl.obolibrary.org/obo/BFO_0000040
 nanomaterial: 
  - NPO 
  - http://purl.bioontology.org/ontology/npo#NPO_199
 nanoparticle: 
  - NPO
  - http://purl.bioontology.org/ontology/npo#NPO_707